# This file has been autogenerated. Do not change by hand.

#' Create a parameter object for the function computeIncidenceRates
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param targetOutcomes  A data frame with two columns: targetId and outcomeId. These columns correspond to cohort IDs in the target and comparator cohort tables.
#' @param riskWindowStart  The start of the risk window (in days) relative to the startAnchor.
#' @param startAnchor  The anchor point for the start of the risk window. Can be "cohort start" or "cohort end".
#' @param riskWindowEnd  The end of the risk window (in days) relative to the endAnchor.
#' @param endAnchor  The anchor point for the end of the risk window. Can be "cohort start" or "cohort end".
#'
#' @export
createComputeIncidenceRatesArgs <- function(targetOutcomes,
                                            riskWindowStart = 0,
                                            startAnchor = "cohort start",
                                            riskWindowEnd = 0,
                                            endAnchor = "cohort end") {
  analysis <- list()
  for (name in names(formals(createComputeIncidenceRatesArgs))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- "args"
  return(analysis)
}
